### ISSUE TITLE
H0nde u suck

### ISSUE THREAD

**Issue by ghost** [h0nde/schttp#2]
Lol H0nde imagine spending ur life for Lego game, so unfair. Being a scammer and getting banned LOL. If you real scammer or “hacker” hack me tho, my user in Roblox “Varoeq” good luck b) 😂
You suck as person. So if u want hack me 1 v1 me in da hood LOL my discord: ww#0892 kid ez 
Hope u will get arrested 
-Varoeq
P.S traps suck 

https://user-images.githubusercontent.com/92826613/137991442-b8cfbbd2-8cc5-4419-a5f8-1f191374d929.MP4

**Comment by Toy0ta** [comment]
![88390BE0-04EE-4705-A883-DE6B97C2F1F5](https://user-images.githubusercontent.com/92826613/137994598-a31565cf-055e-4366-bf00-0f7bdb4e1050.jpeg)

**Comment by atkn1337** [comment]
1v1 in da hood XD fucking retard
